import "@/styles/globals.css";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/header";
import Footer from "@/components/footer";
import { MainContextProvider } from "@/contexts/itemContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-ocean-dark text-white dark:text-white" suppressHydrationWarning={true}>
        <MainContextProvider>
          <Header/>
          {children}
          <Footer/>
        </MainContextProvider>
      </body>
    </html>
  )
}
